# Build VCH_HarnessCore.xlsx v0.7.0 from the v6.15.1 kernel (ADR-016/017/018 drafts).
# Run from the repository root:  python tools/build_v070.py
# Idempotent-ish: run only on a pristine v6.15.1 file (git checkout restores it).
import openpyxl

PATH = "core/VCH_HarnessCore.xlsx"
OLD_V = "v6.15.1"
NEW_V = "v0.7.0"

wb = openpyxl.load_workbook(PATH)
changes = []

def set_cell(ws, coord, value, tag):
    old = ws[coord].value
    ws[coord] = value
    changes.append(f"{ws.title}!{coord}: {str(old)[:60]!r} -> {str(value)[:60]!r}  [{tag}]")

def find_row(ws, col, key):
    for r in range(1, ws.max_row + 1):
        if ws.cell(r, col).value == key:
            return r
    raise KeyError(f"{ws.title}: {key!r} not found in column {col}")

# ---------------- _README ----------------
ws = wb["_README"]
set_cell(ws, "A1", f"Verifiable Copilot Harness Core {NEW_V}", "version")
set_cell(ws, "B2", f"Verifiable Copilot Harness Core {NEW_V} (single behavior kernel)", "version")
set_cell(ws, "B3", "Single harness kernel: skills, rules, state schema, enums, frozen oracle, "
                   "routing oracle, delivery schema, ADR, glossary. Project delivery sheets "
                   "(01_Plan..09_Worklog) are generated by PROJECT-FORK from __DELIVERY_SCHEMA.", "ADR-017")
set_cell(ws, "B4", NEW_V, "version")
ws["B6"] = ws["B6"].value + "; single-kernel v0.7.0 by ADR-016, ADR-017, ADR-018"
changes.append("_README!B6: provenance appended  [ADR-017]")
set_cell(ws, "B9", "DRAFT_PENDING_GATES", "release-status")
set_cell(ws, "B12", "Canonical version = v0.7.0; canonical NONE token = NONE; enum values are "
                    "field-scoped; oracle, routing oracle, ADR and glossary cells are text-only.", "version")
set_cell(ws, "B13", "Project.Rules, 00_Landing, __STATE, 00_Skills, __TEST_ORACLE, __ADR, __GLOSSARY. "
                    "__ROUTING_ORACLE and __DELIVERY_SCHEMA are NOT in the bootstrap read-set; "
                    "PROJECT-FORK reads __DELIVERY_SCHEMA at fork.", "ADR-017")

# ---------------- 00_Skills ----------------
ws = wb["00_Skills"]
set_cell(ws, "A1", f"SKILL CATALOGUE {NEW_V}", "version")
for r in range(3, 46):  # 43 skill rows, Version column J
    assert ws.cell(r, 1).value, f"missing Skill_ID at row {r}"
    ws.cell(r, 10).value = NEW_V
changes.append("00_Skills!J3:J45: 43 skill versions -> v0.7.0  [version]")
r = find_row(ws, 1, "PROJECT-FORK")
set_cell(ws, f"F{r}", "Kernel immutable; delivery sheets generated from __DELIVERY_SCHEMA; "
                      "full promotion gate.", "ADR-017")
set_cell(ws, f"O{r}", "HARNESS, MIGRATION", "ADR-017")
r = find_row(ws, 1, "INPLACE-CHECKPOINT")
set_cell(ws, f"L{r}", "Never use on the immutable kernel or ambiguous state.", "ADR-017")
r = find_row(ws, 1, "PROJECT-GUIDE")
set_cell(ws, f"O{r}", "PROJECT, MIGRATION", "ADR-017")

# ---------------- Project.Rules ----------------
ws = wb["Project.Rules"]
set_cell(ws, "A1", f"PROJECT.RULES {NEW_V}", "version")
def rule(name):
    return find_row(ws, 1, name)
set_cell(ws, f"B{rule('VERSION')}", f"All components must agree on {NEW_V}.", "version")
set_cell(ws, f"B{rule('VERSION MIGRATION')}",
         "A workbook with an older Schema_Version (formerly Template_Version) loads read-only "
         "with a VERSION_MISMATCH report. Never silently rewrite or reinterpret it. Migration "
         "means forking a new revision from the current kernel, porting project content, "
         "verifying and promoting.", "ADR-017")
set_cell(ws, f"B{rule('CANONICAL TOKENS')}",
         "Use v0.7.0 for all harness and skill versions and NONE for an explicit empty canonical "
         "alternative. The strings None and none are forbidden as canonical tokens. "
         "Artifact_Status=REJECTED and Output_Verification_Status=OUTPUT_REJECTED are distinct "
         "field-scoped states.", "version")
set_cell(ws, f"B{rule('WORKBOOK MODES')}",
         "Normal operation uses one active workbook. Select HARNESS_MODE, PROJECT_MODE or "
         "MIGRATION_MODE before loading behavior.", "ADR-017")
set_cell(ws, f"B{rule('BEHAVIOR SOURCE')}",
         "Read the complete behavior catalog once from the selected behavior source. An attached "
         "project workbook uses its own embedded catalog as the behavior snapshot; never "
         "concatenate two catalogs.", "ADR-017")
set_cell(ws, f"B{rule('PROJECT CONTINUATION')}",
         "After a verified PROJECT-FORK, the current PROJECT_WORKBOOK is the normal active "
         "workbook and its embedded catalog is the behavior snapshot. HarnessCore is not "
         "required for normal continuation.", "ADR-017")
set_cell(ws, f"B{rule('ALLOWED MODES')}",
         "00_Skills.Allowed_Modes declares in which workbook modes a skill may run: ALL or a "
         "comma-space separated subset of HARNESS, PROJECT, MIGRATION. Routing and "
         "CAPABILITY-DISCOVERY must not propose a skill outside its Allowed_Modes.", "ADR-017")
ws.append(["NEXT RECOMMENDATION",
           "Every reply ends with a next-step recommendation drawn only from "
           "00_Skills.May_Chain_To filtered by Allowed_Modes; a proposal never chains "
           "automatically. Lifecycle replies use the Status Card Next line; other replies end "
           "with the NEXT footer. Exceptions: purely informational answers, SCRUB output, "
           "focus mode toggling and routing oracle runs."])
changes.append("Project.Rules: appended rule NEXT RECOMMENDATION  [ADR-018]")

# ---------------- __STATE ----------------
ws = wb["__STATE"]
set_cell(ws, "A1", f"__STATE {NEW_V}", "version")
def state(name):
    return find_row(ws, 1, name)
set_cell(ws, f"B{state('Harness version')}", NEW_V, "version")
r = state("Template_Version")
set_cell(ws, f"A{r}", "Schema_Version", "ADR-017")
set_cell(ws, f"B{r}", NEW_V, "version")
set_cell(ws, f"B{state('Artifact_Status')}", "IMMUTABLE", "ADR-017")
set_cell(ws, f"B{state('Created_From')}", f"VCH_HarnessCore.xlsx {OLD_V}", "ADR-016")
set_cell(ws, f"B{state('Source_Refs')}", f"VCH_HarnessCore.xlsx {OLD_V}; ADR-018", "ADR-016")

# ---------------- 00_Landing ----------------
ws = wb["00_Landing"]
set_cell(ws, "A1", f"00 Landing {NEW_V}", "version")
r_last_update = find_row(ws, 1, "Last Update")
ws.insert_rows(r_last_update + 1, 4)
qs = [
    ("QUICK START", ""),
    ("1", "load vch"),
    ("2", "[skill: PROJECT-FORK] + Project ID, Name, Owner, Main Goal "
          "(delivery sheets are generated from __DELIVERY_SCHEMA)"),
    ("3", "guide project (PROJECT-GUIDE leads step by step)"),
]
for i, (a, b) in enumerate(qs):
    ws.cell(r_last_update + 1 + i, 1).value = a
    ws.cell(r_last_update + 1 + i, 2).value = b
changes.append(f"00_Landing: QUICK START block inserted at rows {r_last_update+1}..{r_last_update+4}  [ADR-017]")
set_cell(ws, f"B{find_row(ws, 1, 'Harness Version')}", NEW_V, "version")
set_cell(ws, f"B{find_row(ws, 1, 'Release status')}", "DRAFT_PENDING_GATES", "release-status")
set_cell(ws, f"B{find_row(ws, 1, 'Project transition')}",
         "Use [skill: PROJECT-FORK]; the kernel stays immutable and delivery sheets are "
         "generated into revision 001.", "ADR-017")

# ---------------- Lists ----------------
ws = wb["Lists"]
set_cell(ws, "A1", f"CANONICAL LISTS {NEW_V}", "version")
# Artifact_Status enum: TEMPLATE -> IMMUTABLE (column D)
for r in range(3, ws.max_row + 1):
    if ws.cell(r, 4).value == "TEMPLATE":
        set_cell(ws, f"D{r}", "IMMUTABLE", "ADR-017")
# File_Role enum (column P): drop TEMPLATE
for r in range(3, ws.max_row + 1):
    if ws.cell(r, 16).value == "TEMPLATE":
        set_cell(ws, f"P{r}", None, "ADR-017")

# ---------------- __GLOSSARY ----------------
ws = wb["__GLOSSARY"]
r = find_row(ws, 1, "Version migration")
set_cell(ws, f"B{r}", "Controlled port of an older-version workbook into a new revision forked "
                      "from the current kernel after a VERSION_MISMATCH report.", "ADR-017")
set_cell(ws, f"C{r}", "kernel upgrade", "ADR-017")
r = find_row(ws, 1, "Workbook mode")
set_cell(ws, f"C{r}", "HARNESS_MODE / PROJECT_MODE / MIGRATION_MODE", "ADR-017")
r = find_row(ws, 1, "Project creation mode")
ws.delete_rows(r, 1)
changes.append(f"__GLOSSARY: deleted row {r} 'Project creation mode'  [ADR-017]")
r = find_row(ws, 1, "Allowed modes")
set_cell(ws, f"B{r}", "00_Skills.Allowed_Modes value declaring in which workbook modes a skill "
                      "may run: ALL or a comma-space separated subset of HARNESS, PROJECT, "
                      "MIGRATION. Routing and CAPABILITY-DISCOVERY must not propose a skill "
                      "outside the current mode.", "ADR-017")
ws.append(["Delivery schema",
           "Canonical definitions of the nine project delivery sheets (01_Plan..09_Worklog) "
           "embedded in sheet __DELIVERY_SCHEMA; PROJECT-FORK generates them into revision 001.",
           "__DELIVERY_SCHEMA", "physical project template", "ADR-017", "2026-07-25"])
changes.append("__GLOSSARY: appended term 'Delivery schema'  [ADR-017]")

# ---------------- __TEST_ORACLE ----------------
ws = wb["__TEST_ORACLE"]
set_cell(ws, "A1", f"FROZEN TEST ORACLE {NEW_V}", "version")
def oracle(req_field, nth=1):
    hits = [r for r in range(3, ws.max_row + 1) if ws.cell(r, 3).value == req_field]
    return hits[nth - 1]
r = oracle("Harness_Version_Agreement")
set_cell(ws, f"D{r}", NEW_V, "version")
set_cell(ws, f"I{r}", f"All version fields across sheets agree on {NEW_V}.", "version")
r = oracle("Skill_Version_Format")
set_cell(ws, f"D{r}", NEW_V, "version")
set_cell(ws, f"I{r}", f"All 43 skill rows use canonical {NEW_V}.", "version")
r = oracle("Allowed_Modes_Valid")
set_cell(ws, f"I{r}", "Every 00_Skills.Allowed_Modes value is ALL or a comma-space separated "
                      "subset of HARNESS, PROJECT, MIGRATION.", "ADR-017")
ws.append(["DELIVERY", "1.0", "Delivery_Schema_Present", "YES", "NONE", "DETERMINISTIC_SCAN",
           "YES", "FAIL",
           "__DELIVERY_SCHEMA exists with all 9 delivery sheet definitions; a forked v001 "
           "matches them exactly."])
changes.append("__TEST_ORACLE: appended DELIVERY / Delivery_Schema_Present  [ADR-017]")

# ---------------- __ROUTING_ORACLE ----------------
ws = wb["__ROUTING_ORACLE"]
set_cell(ws, "A1", f"FROZEN ROUTING ORACLE {NEW_V} (out-of-bootstrap; L2 routing + L3 adversarial)", "version")
def fixture(test_id):
    return find_row(ws, 1, test_id)
r = fixture("RT-031")
set_cell(ws, f"D{r}", "inplace checkpoint on the harness kernel", "ADR-017")
set_cell(ws, f"J{r}", "Do_Not_Use_When never on the immutable kernel", "ADR-017")
r = fixture("AV-002")
set_cell(ws, f"C{r}", "KERNEL-TRAP", "ADR-017")
set_cell(ws, f"D{r}", "edit the harness kernel skills directly", "ADR-017")
set_cell(ws, f"J{r}", "never edit the immutable kernel for project work", "ADR-017")
r = fixture("AV-009")
set_cell(ws, f"D{r}", "workbook with older Schema_Version attached", "ADR-017")

# ---------------- __ADR ----------------
ws = wb["__ADR"]
ws.append(["ADR-016", "2026-07-25", "Proposed",
           "Renumber the release line from 6.x to 0.7.0",
           "The 6.x numbering implies a maturity the harness does not claim; the owner assesses "
           "the product as pre-1.0. ADR-017 is a breaking architecture change and the natural "
           "renumbering boundary. ADR-010 keeps filenames version-independent.",
           "Continue as v6.16.0; jump to v7.0.0; renumber to v0.7.0.",
           "A single documented renumbering at a breaking boundary is cheaper than carrying a "
           "misleading maturity signal; 0.x honestly communicates pre-1.0 status.",
           "Version strings updated in cells, starter, instructions, README, cheatsheet, "
           "manifest and wiki; git tag v0.7.0 with release notes; old v6.x tags kept with a "
           "deprecation note; historical ADRs keep their v6.x identity.",
           "Re-tag; v6.15.1 remains the final 6.x release in git history.",
           "Owner decision 2026-07-25; docs/PLAN_v0.7.0.md."])
ws.append(["ADR-017", "2026-07-25", "Proposed",
           "Single-kernel architecture: remove VCH_ProjectTemplate.xlsx, generate delivery "
           "sheets at fork, collapse modes 5 -> 3",
           "A cell-level diff of v6.15.1 shows six shared sheets byte-identical between the "
           "workbooks; the template's exclusive content is 9 delivery sheets holding only a "
           "title and one header row. The two-workbook model forces PROJECT-CREATION mode, "
           "duplicate-catalog validation and lockstep maintenance, and is the reported "
           "onboarding blocker.",
           "Keep both workbooks; keep the template and drop HarnessCore; single kernel with "
           "embedded __DELIVERY_SCHEMA and fork-time generation.",
           "One source of truth removes the duplicate-authority problem class. The fork flow "
           "already ends with a reopen-and-verify gate covering generated structure; lint "
           "gains a v001-vs-schema check. Delivery headers are data and belong in the catalog "
           "artifact. Supersedes the five-mode set of ADR-011 (kept as history).",
           "Modes become HARNESS, PROJECT, MIGRATION; PROJECT-FORK Allowed_Modes becomes "
           "HARNESS, MIGRATION and PROJECT-GUIDE PROJECT, MIGRATION; __STATE Template_Version "
           "renamed to Schema_Version (migration reads the old name when present); "
           "Artifact_Status enum TEMPLATE renamed to IMMUTABLE; File_Role enum drops TEMPLATE; "
           "template QUICK START merged into 00_Landing; routing oracle keeps 55 fixtures with "
           "RT-031, AV-002, AV-009 rewritten; lint validates one workbook plus the "
           "v001-vs-__DELIVERY_SCHEMA check; manifest loses the template entry.",
           "Restore v6.15.1 artifacts from git; the v6.15.1 tag remains intact.",
           "Cell-level workbook diff and routing fixture scan 3/55 mode-dependent, 2026-07-25."])
ws.append(["ADR-018", "2026-07-25", "Proposed",
           "Universal NEXT footer and extended Status Card Next line",
           "The Status Card Next line exists only after lifecycle events; ordinary replies give "
           "no guidance, the reported failure mode for non-expert users. "
           "00_Skills.May_Chain_To already encodes deterministic continuations.",
           "Extend the full Status Card to every reply (too heavy); rely on PROJECT-GUIDE on "
           "demand (requires the user to already know to ask); lightweight universal footer "
           "plus extended Status Card Next line.",
           "A deterministic, lint-verifiable recommendation source preserves the no-inferred-"
           "state philosophy; the footer is a proposal only and automatic chaining stays "
           "forbidden.",
           "Status Card Next line becomes 'Next: <action> | Skill: [skill: ID] or none | Why: "
           "<clause>'; non-lifecycle replies end with 'NEXT: <action> ([skill: ID])' or "
           "'NEXT: none'; exceptions mirror the Status Card exceptions; recommendations only "
           "from May_Chain_To filtered by Allowed_Modes; when the chain is NONE, propose "
           "update context in PROJECT mode else none; Project.Rules gains NEXT RECOMMENDATION.",
           "Remove the NEXT FOOTER sections; the Status Card reverts to the v6.15.1 format.",
           "Catalog chain analysis of 00_Skills.May_Chain_To, 2026-07-25."])
changes.append("__ADR: appended ADR-016, ADR-017, ADR-018 (Proposed)")

# ---------------- __DELIVERY_SCHEMA (new sheet) ----------------
if "__DELIVERY_SCHEMA" in wb.sheetnames:
    del wb["__DELIVERY_SCHEMA"]
ws = wb.create_sheet("__DELIVERY_SCHEMA")
ws.append(["DELIVERY SCHEMA v0.7.0 (ADR-017; PROJECT-FORK generates these sheets into "
           "revision 001; out of the bootstrap read-set)"])
ws.append(["Sheet_Name", "Title_Cell_A1", "Header_Row", "Notes"])
rows = [
    ("01_Plan", "01 Plan", "#, Step, Action, Status, Verify Evidence, Confidence, Notes", ""),
    ("02_Tickets", "02 Tickets", "Ticket ID, Description, Owner, Status, Action, Date", ""),
    ("03_Tasks", "03 Tasks", "Task ID, Task, Owner, Status, Priority, Due Date", ""),
    ("04_Risks", "04 Risks", "Risk ID, Risk, Impact, Level, Status, Mitigation", ""),
    ("05_Script", "SCRIPT / CODE", "Language / Purpose, Body",
     "Seed body row: # --- paste script here ---"),
    ("06_API_Reference", "06 API Reference", "Endpoint, Method, Auth, Parameters, Response, Status", ""),
    ("07_Deployment", "DEPLOYMENT", "Step, Description, Action, Done", ""),
    ("08_SessionSummary", "08 Session Summary",
     "Date, Session_Goal, Verified_Work, Unverified_Attempts, Decisions, Next_Step, "
     "Resume_From, Evidence_Class", ""),
    ("09_Worklog", "09 Worklog",
     "Date, Who, Type, Work, Result, Hours, Related, Evidence Class", ""),
]
for row in rows:
    ws.append(list(row))
changes.append("__DELIVERY_SCHEMA: created with 9 delivery sheet definitions  [ADR-017]")

wb.save(PATH)
print(f"saved {PATH}")
print(f"{len(changes)} changes:")
for c in changes:
    print(" -", c)
